export const queryKeys = {
  currentUser: ["current-user"] as const,
  customers: (filters?: unknown) => ["customers", filters] as const,
  customer: (id: string) => ["customer", id] as const,
  suppliers: (filters?: unknown) => ["suppliers", filters] as const,
  supplier: (id: string) => ["supplier", id] as const,
  stocks: (filters?: unknown) => ["stocks", filters] as const,
  stock: (id: string) => ["stock", id] as const,
  products: (filters?: unknown) => ["products", filters] as const,
  product: (id: string) => ["product", id] as const,
  orders: (filters?: unknown) => ["orders", filters] as const,
  order: (id: string) => ["order", id] as const,
  returns: (filters?: unknown) => ["returns", filters] as const,
  repairs: (filters?: unknown) => ["repairs", filters] as const,
  repair: (id: string) => ["repair", id] as const,
  customerInvoices: (filters?: unknown) => ["customer-invoices", filters] as const,
  customerInvoice: (id: string) => ["customer-invoice", id] as const,
  supplierInvoices: (filters?: unknown) => ["supplier-invoices", filters] as const,
  supplierInvoice: (id: string) => ["supplier-invoice", id] as const,
  customerLedger: (id: string, filters?: unknown) => ["customer-ledger", id, filters] as const,
  supplierLedger: (id: string, filters?: unknown) => ["supplier-ledger", id, filters] as const,
  dashboard: (dateRange?: unknown) => ["dashboard", dateRange] as const,
  dashboardSalesChart: (dateRange?: unknown, type?: string) =>
    ["dashboard-sales-chart", dateRange, type] as const,
} as const;
