export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  profile: "/profile",
  dashboard: "/dashboard",
  customers: "/customers",
  customerNew: "/customers/new",
  customerDetail: (id: string) => `/customers/${id}`,
  suppliers: "/suppliers",
  supplierNew: "/suppliers/new",
  supplierDetail: (id: string) => `/suppliers/${id}`,
  stock: "/stock",
  stockNew: "/stock/new",
  stockDetail: (id: string) => `/stock/${id}`,
  products: "/products",
  productDetail: (id: string) => `/products/${id}`,
  orders: "/orders",
  orderNew: "/orders/new",
  orderDetail: (id: string) => `/orders/${id}`,
  orderEdit: (id: string) => `/orders/${id}/edit`,
  returns: "/returns",
  returnNew: "/returns/new",
  repairs: "/repairs",
  repairNew: "/repairs/new",
  repairDetail: (id: string) => `/repairs/${id}`,
  customerInvoices: "/finance/customer-invoices",
  customerInvoiceDetail: (id: string) => `/finance/customer-invoices/${id}`,
  supplierInvoices: "/finance/supplier-invoices",
  supplierInvoiceDetail: (id: string) => `/finance/supplier-invoices/${id}`,
  customerLedger: (id: string) => `/finance/customer-ledger/${id}`,
  supplierLedger: (id: string) => `/finance/supplier-ledger/${id}`,
} as const;

export const PUBLIC_ROUTES: string[] = [ROUTES.login, ROUTES.register];
